import { Ticket } from '../../core';

export const ticketList: Array<Ticket> = [
  {
    id: 1,
    user: {
      telNo: '01234567891',
      name: 'أحمد مصطفي',
      profileImage: 'assets/images/1.jpg',
    },
    ticketNo: 'C-101',
    ticketPrice: '40',
    cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
    peopleNo: 1,
    purchaseNo: 'مرة واحدة',
    ticket: {
      fileName: 'تذكرة رقم 45.pdf',
      filesize: '9mb - Pdf',
    },
  },
  {
    id: 2,
    user: {
      telNo: '01234567891',
      name: 'علي مصطفي',
      profileImage: 'assets/images/2.jpg',
    },
    ticketNo: 'C-101',
    ticketPrice: '45',
    cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
    peopleNo: 1,
    purchaseNo: 'مرة واحدة',
    ticket: {
      fileName: 'تذكرة رقم 45.pdf',
      filesize: '9mb - Pdf',
    },
  },
  {
    id: 3,
    user: {
      telNo: '01234567891',
      name: 'محمد مصطفي',
      profileImage: 'assets/images/3.jpg',
    },
    ticketNo: 'C-101',
    ticketPrice: '50',
    cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
    peopleNo: 1,
    purchaseNo: 'مرة واحدة',
    ticket: {
      fileName: 'تذكرة رقم 45.pdf',
      filesize: '9mb - Pdf',
    },
  },
  {
    id: 4,
    user: {
      telNo: '01234567891',
      name: 'محمد مصطفي',
      profileImage: 'assets/images/3.jpg',
    },
    ticketNo: 'C-101',
    ticketPrice: '50',
    cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
    peopleNo: 1,
    purchaseNo: 'مرة واحدة',
    ticket: {
      fileName: 'تذكرة رقم 45.pdf',
      filesize: '9mb - Pdf',
    },
  },
  {
    id: 5,
    user: {
      telNo: '01234567891',
      name: 'محمد مصطفي',
      profileImage: 'assets/images/3.jpg',
    },
    ticketNo: 'C-101',
    ticketPrice: '50',
    cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
    peopleNo: 1,
    purchaseNo: 'مرة واحدة',
    ticket: {
      fileName: 'تذكرة رقم 45.pdf',
      filesize: '9mb - Pdf',
    },
  },
  {
    id: 6,
    user: {
      telNo: '01234567891',
      name: 'محمد مصطفي',
      profileImage: 'assets/images/3.jpg',
    },
    ticketNo: 'C-101',
    ticketPrice: '50',
    cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
    peopleNo: 1,
    purchaseNo: 'مرة واحدة',
    ticket: {
      fileName: 'تذكرة رقم 45.pdf',
      filesize: '9mb - Pdf',
    },
  },
  {
    id: 7,
    user: {
      telNo: '01234567891',
      name: 'محمد مصطفي',
      profileImage: 'assets/images/3.jpg',
    },
    ticketNo: 'C-101',
    ticketPrice: '50',
    cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
    peopleNo: 1,
    purchaseNo: 'مرة واحدة',
    ticket: {
      fileName: 'تذكرة رقم 45.pdf',
      filesize: '9mb - Pdf',
    },
  },
  {
    id: 8,
    user: {
      telNo: '01234567891',
      name: 'محمد مصطفي',
      profileImage: 'assets/images/3.jpg',
    },
    ticketNo: 'C-101',
    ticketPrice: '50',
    cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
    peopleNo: 1,
    purchaseNo: 'مرة واحدة',
    ticket: {
      fileName: 'تذكرة رقم 45.pdf',
      filesize: '9mb - Pdf',
    },
  },
  {
    id: 9,
    user: {
      telNo: '01234567891',
      name: 'محمد مصطفي',
      profileImage: 'assets/images/3.jpg',
    },
    ticketNo: 'C-101',
    ticketPrice: '50',
    cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
    peopleNo: 1,
    purchaseNo: 'مرة واحدة',
    ticket: {
      fileName: 'تذكرة رقم 45.pdf',
      filesize: '9mb - Pdf',
    },
  },
  {
    id: 10,
    user: {
      telNo: '01234567891',
      name: 'محمد مصطفي',
      profileImage: 'assets/images/3.jpg',
    },
    ticketNo: 'C-101',
    ticketPrice: '50',
    cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
    peopleNo: 1,
    purchaseNo: 'مرة واحدة',
    ticket: {
      fileName: 'تذكرة رقم 45.pdf',
      filesize: '9mb - Pdf',
    },
  },
  {
    id: 10,
    user: {
      telNo: '01234567891',
      name: 'محمد مصطفي',
      profileImage: 'assets/images/3.jpg',
    },
    ticketNo: 'C-101',
    ticketPrice: '50',
    cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
    peopleNo: 1,
    purchaseNo: 'مرة واحدة',
    ticket: {
      fileName: 'تذكرة رقم 45.pdf',
      filesize: '9mb - Pdf',
    },
  },
  {
    id: 10,
    user: {
      telNo: '01234567891',
      name: 'محمد مصطفي',
      profileImage: 'assets/images/3.jpg',
    },
    ticketNo: 'C-101',
    ticketPrice: '50',
    cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
    peopleNo: 1,
    purchaseNo: 'مرة واحدة',
    ticket: {
      fileName: 'تذكرة رقم 45.pdf',
      filesize: '9mb - Pdf',
    },
  },
  {
    id: 10,
    user: {
      telNo: '01234567891',
      name: 'محمد مصطفي',
      profileImage: 'assets/images/3.jpg',
    },
    ticketNo: 'C-101',
    ticketPrice: '50',
    cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
    peopleNo: 1,
    purchaseNo: 'مرة واحدة',
    ticket: {
      fileName: 'تذكرة رقم 45.pdf',
      filesize: '9mb - Pdf',
    },
  },
  {
    id: 10,
    user: {
      telNo: '01234567891',
      name: 'محمد مصطفي',
      profileImage: 'assets/images/3.jpg',
    },
    ticketNo: 'C-101',
    ticketPrice: '50',
    cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
    peopleNo: 1,
    purchaseNo: 'مرة واحدة',
    ticket: {
      fileName: 'تذكرة رقم 45.pdf',
      filesize: '9mb - Pdf',
    },
  },
  {
    id: 10,
    user: {
      telNo: '01234567891',
      name: 'محمد مصطفي',
      profileImage: 'assets/images/3.jpg',
    },
    ticketNo: 'C-101',
    ticketPrice: '50',
    cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
    peopleNo: 1,
    purchaseNo: 'مرة واحدة',
    ticket: {
      fileName: 'تذكرة رقم 45.pdf',
      filesize: '9mb - Pdf',
    },
  },
  {
    id: 10,
    user: {
      telNo: '01234567891',
      name: 'محمد مصطفي',
      profileImage: 'assets/images/3.jpg',
    },
    ticketNo: 'C-101',
    ticketPrice: '50',
    cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
    peopleNo: 1,
    purchaseNo: 'مرة واحدة',
    ticket: {
      fileName: 'تذكرة رقم 45.pdf',
      filesize: '9mb - Pdf',
    },
  },
  {
    id: 10,
    user: {
      telNo: '01234567891',
      name: 'محمد مصطفي',
      profileImage: 'assets/images/3.jpg',
    },
    ticketNo: 'C-101',
    ticketPrice: '50',
    cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
    peopleNo: 1,
    purchaseNo: 'مرة واحدة',
    ticket: {
      fileName: 'تذكرة رقم 45.pdf',
      filesize: '9mb - Pdf',
    },
  },
  {
    id: 10,
    user: {
      telNo: '01234567891',
      name: 'محمد مصطفي',
      profileImage: 'assets/images/3.jpg',
    },
    ticketNo: 'C-101',
    ticketPrice: '50',
    cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
    peopleNo: 1,
    purchaseNo: 'مرة واحدة',
    ticket: {
      fileName: 'تذكرة رقم 45.pdf',
      filesize: '9mb - Pdf',
    },
  },
  {
    id: 10,
    user: {
      telNo: '01234567891',
      name: 'محمد مصطفي',
      profileImage: 'assets/images/3.jpg',
    },
    ticketNo: 'C-101',
    ticketPrice: '50',
    cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
    peopleNo: 1,
    purchaseNo: 'مرة واحدة',
    ticket: {
      fileName: 'تذكرة رقم 45.pdf',
      filesize: '9mb - Pdf',
    },
  },
  {
    id: 10,
    user: {
      telNo: '01234567891',
      name: 'محمد مصطفي',
      profileImage: 'assets/images/3.jpg',
    },
    ticketNo: 'C-101',
    ticketPrice: '50',
    cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
    peopleNo: 1,
    purchaseNo: 'مرة واحدة',
    ticket: {
      fileName: 'تذكرة رقم 45.pdf',
      filesize: '9mb - Pdf',
    },
  },
  {
    id: 10,
    user: {
      telNo: '01234567891',
      name: 'محمد مصطفي',
      profileImage: 'assets/images/3.jpg',
    },
    ticketNo: 'C-101',
    ticketPrice: '50',
    cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
    peopleNo: 1,
    purchaseNo: 'مرة واحدة',
    ticket: {
      fileName: 'تذكرة رقم 45.pdf',
      filesize: '9mb - Pdf',
    },
  },
  {
    id: 10,
    user: {
      telNo: '01234567891',
      name: 'محمد مصطفي',
      profileImage: 'assets/images/3.jpg',
    },
    ticketNo: 'C-101',
    ticketPrice: '50',
    cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
    peopleNo: 1,
    purchaseNo: 'مرة واحدة',
    ticket: {
      fileName: 'تذكرة رقم 45.pdf',
      filesize: '9mb - Pdf',
    },
  },
  {
    id: 10,
    user: {
      telNo: '01234567891',
      name: 'محمد مصطفي',
      profileImage: 'assets/images/3.jpg',
    },
    ticketNo: 'C-101',
    ticketPrice: '50',
    cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
    peopleNo: 1,
    purchaseNo: 'مرة واحدة',
    ticket: {
      fileName: 'تذكرة رقم 45.pdf',
      filesize: '9mb - Pdf',
    },
  },
  {
    id: 10,
    user: {
      telNo: '01234567891',
      name: 'محمد مصطفي',
      profileImage: 'assets/images/3.jpg',
    },
    ticketNo: 'C-101',
    ticketPrice: '50',
    cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
    peopleNo: 1,
    purchaseNo: 'مرة واحدة',
    ticket: {
      fileName: 'تذكرة رقم 45.pdf',
      filesize: '9mb - Pdf',
    },
  },
  {
    id: 10,
    user: {
      telNo: '01234567891',
      name: 'محمد مصطفي',
      profileImage: 'assets/images/3.jpg',
    },
    ticketNo: 'C-101',
    ticketPrice: '50',
    cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
    peopleNo: 1,
    purchaseNo: 'مرة واحدة',
    ticket: {
      fileName: 'تذكرة رقم 45.pdf',
      filesize: '9mb - Pdf',
    },
  },
  {
    id: 10,
    user: {
      telNo: '01234567891',
      name: 'محمد مصطفي',
      profileImage: 'assets/images/3.jpg',
    },
    ticketNo: 'C-101',
    ticketPrice: '50',
    cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
    peopleNo: 1,
    purchaseNo: 'مرة واحدة',
    ticket: {
      fileName: 'تذكرة رقم 45.pdf',
      filesize: '9mb - Pdf',
    },
  },
  {
    id: 10,
    user: {
      telNo: '01234567891',
      name: 'محمد مصطفي',
      profileImage: 'assets/images/3.jpg',
    },
    ticketNo: 'C-101',
    ticketPrice: '50',
    cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
    peopleNo: 1,
    purchaseNo: 'مرة واحدة',
    ticket: {
      fileName: 'تذكرة رقم 45.pdf',
      filesize: '9mb - Pdf',
    },
  },
  {
    id: 10,
    user: {
      telNo: '01234567891',
      name: 'محمد مصطفي',
      profileImage: 'assets/images/3.jpg',
    },
    ticketNo: 'C-101',
    ticketPrice: '50',
    cinema: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة',
    peopleNo: 1,
    purchaseNo: 'مرة واحدة',
    ticket: {
      fileName: 'تذكرة رقم 45.pdf',
      filesize: '9mb - Pdf',
    },
  },
];
